axis_linear_x: 1 # Left thumb stick vertical
scale_linear_x: 0.7
scale_linear_x_turbo: 1.5

axis_linear_y: 0 # Left thumb stick horizontal
scale_linear_y: 0.7
scale_linear_y_turbo: 1.5

axis_angular: 3 # Right thumb stick horizontal
scale_angular: 0.7

enable_button: 5 # Left trigger button
enable_turbo_button: 6 # Right trigger button
